### ISSUE TITLE
create room issue

### ISSUE THREAD

**Issue by deepakmehta206** [IEvangelist/IEvangelist.VideoChat#15]
room creating for other participants is not working any more please reslove it

**Comment by IEvangelist** [comment]
Hi @deepakmehta206,

Thank you for posting an issue. I have a few clarifying questions.

- What exact error are you experiencing?
- Where does it fail in the code, exactly (what line number, client side, server side, etc)?
- Is this for all users?
- When did this error start occurring?
- Did anything else change?

I just tested this out, and it works perfectly. I'm not sure, but I'll need more details from you.

**Comment by deepakmehta206** [comment]
sorry its my mistake i got error from twillo  because i am using it test sid which is not configured correctly, thanks for your reply
