### ISSUE TITLE
Not working on mobile browsers

### ISSUE THREAD

**Issue by SammaniPalan** [IEvangelist/IEvangelist.VideoChat#2]
Hi,
I tried using this app in the mobile browsers. When using desktop browsers video's of the participant  getting synced without an issue. But when an participant joined from a mobile browser it takes 4-5 minutes to sync. Do you have any idea on how to fix that issue? Would be a great help

**Comment by IEvangelist** [comment]
Hi @SammaniPalan,

Thank you for playing with this app. I'm not really sure why that would take so long, that seems crazy to me and I honestly didn't try that. I wonder if the JavaScript SDK has any known issues for slow mobile connectivity. 

Additionally, I haven't yet upgraded to the latest version - which may or may not help. https://www.npmjs.com/package/twilio-video, I see that v1.18.2 is available now - but I've been on the beta version. Also, look at the browser support too https://www.npmjs.com/package/twilio-video#browser-support... no mention of mobile. 🤷‍♂
