### ISSUE TITLE
How to composition video and audio file?

### ISSUE THREAD

**Issue by SriSamVictor** [IEvangelist/IEvangelist.VideoChat#25]
I already done with creation of the room and recordings but the recording files should be video and audio with unique room id and my question is how to composition video and audio file in twilio? please any help me for this 

Thanks in advance

**Comment by IEvangelist** [comment]
Hi @SriSamVictor

This app does not include recording functionality, nor was that intended as part of the original scope. If you add recording, please share the code that does that in its entirety here and I'll have a look at it. Otherwise, you might have to ask support folks at Twilio. Thank you

> **_Important:_**
> This app is a demo app, not intended for production scenarios.

**Comment by IEvangelist** [comment]
Closing this as there has been no reply from the user.
