### ISSUE TITLE
Raise Hand,  Mute All, Remove Participants

### ISSUE THREAD

**Issue by himanshukm-sdei** [IEvangelist/IEvangelist.VideoChat#29]
We are facing issue to implement  Mute All Participants, Raise Hand ,Remove Participants. Please provide solution. We are using your Repo

**Comment by himanshukm-sdei** [comment]
Any update . This will save our  time

**Comment by IEvangelist** [comment]
Hi @himanshukm-sdei - this repo is yours to use, but it is a bit unreasonable to assume that I can simply drop everything else that I'm working on to support several new features so quickly. You're literally asking for three new features.

Part of being open source is that you're allowed to take the source, and add these features yourself. I do apologize for any convenience but I'm buried with many other things right now.
