### ISSUE TITLE
Issue in firefox, does not connect to room

### ISSUE THREAD

**Issue by vipinpcube** [IEvangelist/IEvangelist.VideoChat#42]
I checked demo example in firefox web browser and found issue to connect room.
Below url
https://ievangelist-videochat.azurewebsites.net
![image](https://user-images.githubusercontent.com/97298756/148561017-1d825db8-8a05-42ee-8ca2-362daf7c985c.png)
/

**Comment by IEvangelist** [comment]
I just now tested this on FireFox, and it seems to be working.

![image](https://user-images.githubusercontent.com/7679720/148573337-8e205169-bf49-4b06-89f8-03b7a33f312b.png)

Here is the version I'm using, maybe try upgrading your browser and hard refreshing?

![image](https://user-images.githubusercontent.com/7679720/148573459-93db38f6-a07b-440f-b9a5-967d49ffad8b.png)

Here's a test room too:

![image](https://user-images.githubusercontent.com/7679720/148573576-c35dd0a6-e30e-49d8-b003-ce5e1178c7c4.png)

**Comment by vipinpcube** [comment]
Thanks for reply. i uninstalled firefox & install again now its working fine.
Thanks
