### ISSUE TITLE
Element implicitly has an 'any' type because index expression is not of type 'number'

### ISSUE THREAD

**Issue by sangheraajit** [IEvangelist/IEvangelist.VideoChat#50]
We are getting the following error

Element implicitly has an 'any' type because index expression is not of type 'number'

method name

```ts
private async tryGetDevices() {
        const mediaDevices = await navigator.mediaDevices.enumerateDevices();
        console.log("mediaDevices",mediaDevices)
       //return mediaDevices;
     const devices = ['audioinput', 'audiooutput', 'videoinput'].reduce((options , kind) => {
            return options[kind] = mediaDevices.filter(device => device.kind === kind);
        }, [] as Devices);
        return devices;         
    }
```

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/12188266/160827438-f6343e9b-19b6-4405-a250-00d178a406f6.png">

**Comment by IEvangelist** [comment]
Hi @sangheraajit - I think you might be able to solve this by adding this to the tsconfig.json.

```json
{
    "suppressImplicitAnyIndexErrors": true
}
```

**Comment by sangheraajit** [comment]
Hi,
Thanks that's works. But this seems workaround we should fix the issue.

**Comment by IEvangelist** [comment]
@sangheraajit
I always welcome pull requests, please submit one with your fix and I'll happily review it, and likely merge it in. Reference this issue when you do. If you're not able to submit a PR, we can close this issue as the code works.
